<a href="https://colab.research.google.com/github/239y1a3931-sudo/Agentic-AI/blob/main/day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b=np.array([[1,2,3],
            [4,4,6],
            [7,8,9]])
print(b)

[[1 2 3]
 [4 4 6]
 [7 8 9]]


In [ ]:
c=np.array([
    [
        [1,2]
    ],
    [
        [4,5]
    ]

])
print(c)

[[[1 2]]

 [[4 5]]]


In [ ]:
z=np.zeros([3,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
y=np.ones([4,4])
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
x=np.full([3,3],5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
w=np.eye(4)
print(w)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(z,y,x,w)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] [[5 5 5]
 [5 5 5]
 [5 5 5]] [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
f=np.arange(1,11,2)
print(f)

[1 3 5 7 9]


In [ ]:
g=np.linspace(2,4,6)
print(g)

[2.  2.4 2.8 3.2 3.6 4. ]


In [ ]:
np.random.rand(1,5)

array([[0.04683163, 0.7699474 , 0.7274576 , 0.67367989, 0.00814638]])

In [ ]:
np.random.randint(1,5,size=(5,10))

array([[2, 2, 1, 2, 3, 2, 4, 3, 2, 1],
       [2, 4, 4, 1, 4, 2, 4, 1, 4, 4],
       [3, 3, 4, 3, 1, 4, 3, 3, 3, 4],
       [2, 4, 2, 1, 1, 1, 1, 1, 4, 2],
       [1, 3, 3, 1, 2, 3, 2, 1, 2, 3]])

In [ ]:
np.random.randn(4,9)

array([[ 1.46463795, -0.53521245,  0.43515194,  0.35968685, -1.52617819,
        -0.63557464, -2.02905707,  0.06953465, -0.32491896],
       [-1.70131988, -1.40376255, -0.20190024,  0.71319695, -0.44996174,
         1.8354288 , -1.01925162, -0.26019725, -0.98048764],
       [ 0.25014056,  0.23875701,  0.05239322, -0.11072774, -0.37968381,
         1.07065006,  1.07583302,  1.06376109, -0.62196131],
       [ 0.26671028, -0.30692977, -1.21044782,  1.53741223,  2.83079308,
         1.72494317,  1.58568827,  0.43420829, -0.40804038]])

In [ ]:
arr=np.array([[1,2,3],[4,6,7]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[1 2 3]
 [4 6 7]]
(2, 3)
2
6
int64


In [ ]:
print(a[-1])
print(a[1:4])
print(a[::3])
print(a[:3])
print(a[::-1])


4
[2 3 4]
[1 4]
[1 2 3]
[4 3 2 1]


In [ ]:
print(b[2,2])
print(b[-1,-2])
print(b[::1,2])
print(b[:,1])
print(b[0,:])
print(b[::-1])
print(b[0:1,0:1])
print(b)

9
8
[3 6 9]
[2 4 8]
[1 2 3]
[[7 8 9]
 [4 4 6]
 [1 2 3]]
[[1]]
[[1 2 3]
 [4 4 6]
 [7 8 9]]


In [ ]:
arr=np.array([1,22,44,5,57])
mask= arr>15
print(mask)
print(arr[mask])
#shorthanddddddd

print(arr[arr>15])
print(arr[0:3])

[False  True  True False  True]
[22 44 57]
[22 44 57]
[ 1 22 44]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a**2)
print(a+10)

[1 4 9]
[11 12 13]


In [ ]:
a=np.array([2.4,6.0,5.0])
np.floor(a)
np.ceil(a)
np.round(a,2)

array([2.4, 6. , 5. ])

In [ ]:
array=np.arange(2,20,2)
print(array)
mx=np.max(array)
arg=np.argmax(array)
print(mx)
print(arg)

[ 2  4  6  8 10 12 14 16 18]
18
8


In [ ]:
arr=np.arange(0,50,2)
print(arr)
b=arr.reshape(5,5)
print(b)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
